version: '3.9'

services:
  mysql:
    image: mysql:8.0.22
    hostname: mysql
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=eoloplantsDB
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  mongo:
    image: mongo:jammy
    hostname: mongo
    restart: always
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_INITDB_DATABASE=topo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password     
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=password  
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  rabbitmq:
    image: rabbitmq:3.11.10
    hostname: rabbitmq
    restart: always
    environment:
      - RABBIT_PORT=5672
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASS=guest    
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  server:
    image: garrijuan/server:v1.3
    hostname: server
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=eoloplantsDB
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - RABBIT_PORT=5672
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASS=guest 
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    
  weatherservice:
    image: garrijuan/weatherservice:v1.3
    hostname: weatherservice
    environment:
      - WEATHER_PORT=9090
      - WEATHER_HOST=weatherservice
    ports:
      - 9090:9090
    restart: on-failure
    
  planner:
    image: garrijuan/planner:v1.3
    hostname: planner
    environment:
      - TOPO_HOST=toposervice
      - TOPO_PORT=8181
      - GRPC_HOST=weatherservice
      - GRPC_PORT=9090
      - RABBIT_PORT=5672
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASS=guest       
    depends_on:
      - weatherservice
      - toposervice
      - rabbitmq
    command: >
      /bin/sh -c "./wait-for-it.sh weatherservice:9090 --timeout=0 
      && ./wait-for-it.sh rabbitmq:5672 --timeout=0 
      && ./wait-for-it.sh toposervice:8181 --timeout=0 
      && java -jar planner-v0.2.jar"
      
  toposervice:
    image: garrijuan/toposervice:v1.3
    hostname: toposervice
    restart: on-failure
    environment:
      - TOPO_PORT=8181
      - TOPO_HOST=toposervice
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_INITDB_DATABASE=topo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password     
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=password
    ports:
      - 8181:8181 
    depends_on:
      - mongo
    #healthcheck:
      #test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      #test: ["CMD", "mongo", "--username", "user", "--password", "password", "--eval", "db.adminCommand('ping')"]
      #interval: 5s
      #timeout: 5s
      #retries: 5
      #start_period: 10s
          